import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/shared/context/SidebarContext";
import { Header } from "@/widgets/Header/Header";
import Sidebar from "@/widgets/Sidebar/Sidebar";
import { ApplySidebarSpacing } from "@/shared/hooks/useApplySidebarSpacing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#0B1020] text-white">
        <SidebarProvider>
          <Header />
          <Sidebar />
          <ApplySidebarSpacing />
          {/* смещение контента: когда sidebar открыт 264px, иначе 72px; на мобилке нет смещения */}
          <main className="pt-16 md:transition-all md:duration-200 md:ml-[264px] data-[compact=true]:md:ml-[72px]" id="app-main">
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
